/**
 * Discount Forklift Spiff Tracker - Initial Administrator Bootstrap Utility
 * Usage:
 *   npx tsx scripts/create-initial-admin.ts [email] [name] [password]
 *
 * Example:
 *   npx tsx scripts/create-initial-admin.ts caleb@discountforkliftphoenix.com "Caleb Vance" "InitialAdmin2026!"
 *
 * If no password is provided, a cryptographically strong 16-character password is generated.
 * Password is salted (16-byte random salt) and hashed using scrypt. Plaintext passwords are NEVER stored.
 */

import 'dotenv/config';
import crypto from 'crypto';
import { db, schema, isNeonConfigured } from '../src/db/index';
import { eq } from 'drizzle-orm';
import { hashPassword, validatePasswordStrength } from '../src/lib/auth';
import { createAdminAuthToken } from '../src/lib/authTokens';
import { memoryStore } from '../src/lib/repository';

async function main() {
  console.log('====================================================');
  console.log(' DISCOUNT FORKLIFT - INITIAL ADMINISTRATOR SETUP');
  console.log('====================================================\n');

  const emailArg = process.argv[2] || process.env.INITIAL_ADMIN_EMAIL || 'caleb@discountforkliftphoenix.com';
  const nameArg = process.argv[3] || process.env.INITIAL_ADMIN_NAME || 'Caleb Vance';
  let passwordArg = process.argv[4] || process.env.INITIAL_ADMIN_PASSWORD;

  const email = emailArg.trim().toLowerCase();
  const name = nameArg.trim();

  let isAutoGenerated = false;
  if (!passwordArg) {
    // Generate a strong random temporary password
    const randChars = crypto.randomBytes(8).toString('hex');
    passwordArg = `Admin#${randChars}A1`;
    isAutoGenerated = true;
  }

  const strength = validatePasswordStrength(passwordArg);
  if (!strength.isValid) {
    console.error(`✗ Error: Password does not meet security requirements: ${strength.error}`);
    process.exit(1);
  }

  const pHash = hashPassword(passwordArg);
  const now = new Date();
  const adminId = `admin_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`;

  console.log(`Setting up Administrator Account:`);
  console.log(`  Email: ${email}`);
  console.log(`  Name:  ${name}`);
  console.log(`  Role:  Administrator`);

  if (isNeonConfigured && db) {
    try {
      console.log('Connecting to Neon PostgreSQL database...');
      const existing = await db
        .select()
        .from(schema.adminUsers)
        .where(eq(schema.adminUsers.email, email))
        .limit(1);

      let targetId = adminId;
      if (existing.length > 0) {
        const u = existing[0];
        targetId = u.id;
        if (u.passwordHash) {
          // If this email already exists and already has a password: grant admin role without changing password
          await db
            .update(schema.adminUsers)
            .set({
              role: 'Administrator',
              isAuthorized: true,
              updatedAt: now,
            })
            .where(eq(schema.adminUsers.id, u.id));

          console.log(`✓ Existing administrator record found (ID: ${u.id}). Granted Administrator role; existing password preserved.`);
        } else {
          // Placeholder account without password: set initial password with mustChangePassword = true
          await db
            .update(schema.adminUsers)
            .set({
              name,
              role: 'Administrator',
              passwordHash: pHash,
              isAuthorized: true,
              mustChangePassword: true,
              passwordChangedAt: now,
              updatedAt: now,
            })
            .where(eq(schema.adminUsers.id, u.id));

          console.log(`✓ Set initial password for account (ID: ${u.id}). Password change required on first login.`);
        }
      } else {
        await db.insert(schema.adminUsers).values({
          id: adminId,
          email,
          name,
          role: 'Administrator',
          passwordHash: pHash,
          isAuthorized: true,
          mustChangePassword: true,
          passwordChangedAt: now,
          createdAt: now,
          updatedAt: now,
        });

        console.log(`✓ Inserted new administrator record (ID: ${adminId}) into Neon. Password change required on first login.`);
      }

      // Generate a single-use setup/reset token as well for convenience
      const { rawToken } = await createAdminAuthToken({
        adminId: targetId,
        tokenType: 'initial_setup',
        createdBy: 'CLI Bootstrap Script',
      });

      console.log('\n----------------------------------------------------');
      console.log('✓ Administrator setup completed successfully in Neon!');
      console.log('----------------------------------------------------');
      if (isAutoGenerated) {
        console.log(`Initial Password Generated: ${passwordArg}`);
        console.log('Please record this password or change it immediately upon login.');
      } else {
        console.log('Password has been securely salted and hashed.');
      }
      console.log(`Optional Single-Use Setup Token: ${rawToken}`);
      console.log('====================================================\n');
      process.exit(0);
    } catch (err: any) {
      console.error('✗ Neon database error during administrator setup:', err.message);
      process.exit(1);
    }
  } else {
    console.log('ℹ Notice: DATABASE_URL not configured. Updating local memory store.');
    const memIdx = memoryStore.adminUsers.findIndex((u) => u.email.toLowerCase() === email);
    if (memIdx >= 0) {
      if (memoryStore.adminUsers[memIdx].passwordHash) {
        // Preserve password
        memoryStore.adminUsers[memIdx].role = 'Administrator';
        memoryStore.adminUsers[memIdx].isAuthorized = true;
        console.log(`✓ Existing record found. Granted Administrator role; existing password preserved.`);
      } else {
        memoryStore.adminUsers[memIdx].name = name;
        memoryStore.adminUsers[memIdx].role = 'Administrator';
        memoryStore.adminUsers[memIdx].passwordHash = pHash;
        memoryStore.adminUsers[memIdx].mustChangePassword = true;
        memoryStore.adminUsers[memIdx].passwordChangedAt = now.toISOString();
        memoryStore.adminUsers[memIdx].isAuthorized = true;
        console.log(`✓ Initial password established. Password change required on first login.`);
      }
    } else {
      memoryStore.adminUsers.push({
        id: adminId,
        email,
        name,
        role: 'Administrator',
        passwordHash: pHash,
        isAuthorized: true,
        mustChangePassword: true,
        lastLoginAt: null,
        passwordChangedAt: now.toISOString(),
        createdAt: now.toISOString(),
        updatedAt: now.toISOString(),
      });
      console.log(`✓ New administrator created. Password change required on first login.`);
    }

    console.log('\n----------------------------------------------------');
    console.log('✓ Administrator account initialized in memory store.');
    if (isAutoGenerated) {
      console.log(`Initial Password Generated: ${passwordArg}`);
    }
    console.log('====================================================\n');
    process.exit(0);
  }
}

main().catch((err) => {
  console.error('Fatal error during setup:', err);
  process.exit(1);
});
